name: TN Auto Build

on:
  workflow_dispatch:
    inputs:
     ROM_URL:
      description: 'OTA Url ROM'
      default: 'https://bn.d.miui.com/OS1.0.24.6.17.DEV/miui_FUXI_OS1.0.24.6.17.DEV_dc97d0a93b_14.0.zip'
      required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout
        uses: actions/checkout@main
        
      - name: Update timezone Vietnam
        run: |
           sudo timedatectl set-timezone Asia/Ho_Chi_Minh
           
      - name: PREPARE ENVIRONMENT
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 python3 p7zip-full zipalign android-sdk-libsparse-utils lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python-is-python3
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE }}" > token.txt
          #cp token.txt ~/.config/rclone/rclone.conf
          base64 -d token.txt > ~/.config/rclone/rclone.conf

      - name: Clone Git TN
        run: |
          git clone -b 2.5 https://${{ secrets.TNKEY }}@github.com/nvthang2303/HyperTN.git
          
      - name: Auto build TN (VIET)
        run: |
          cd HyperTN
           sudo chmod 777 -R *
           sudo bash BuildTN_vn.sh ${{ github.event.inputs.ROM_URL }}
      - name: Clone Git TN
        run: |
          rm -rf HyperTN
          git clone -b 2.5 https://${{ secrets.TNKEY }}@github.com/nvthang2303/HyperTN.git
      - name: Auto build TN (MULTI)
        run: |
          cd HyperTN
           sudo chmod 777 -R *
           sudo bash BuildTN_multi.sh ${{ github.event.inputs.ROM_URL }}
      
